name: Test Pull Request
on:
    pull_request:
        branches:
            - main
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: "1.22.4"
            - name: Install Dependencies
              run: go mod download
            - name: Run Tests
              run: go test ./... -v

